name: Checkrun

on:
  check_run: 
    types: [ completed ]

jobs:
  release:
   if: ${{ github.event.check_run.app.name == 'CircleCI Checks' && github.event.check_run.conclusion == 'success' && github.event.check_run.name == 'build-deploy' }}
   runs-on: ubuntu-latest
   steps:
      - uses: hmarr/debug-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set version
        shell: bash
        run: |
          COMMIT_HASH=${{ github.sha }}
          DATE=$(date '+%Y%m%d%H%M%S')
          VERSION=1.0.${{github.run_number}}-${DATE}.commit-${COMMIT_HASH::7}
          echo ${VERSION}
          echo "##[set-output name=number;]$(echo ${VERSION})"
          echo ${VERSION} > hello_world
        id: set_version
      - name: Check last commit release
        shell: bash
        run: |
          # Get current commit hash
          NEW_COMMIT_HASH=$(echo -n ${{ github.sha }} | tail -c 7)

          # Fetch last version
          LAST_VERSION=$(curl https://api.github.com/repos/decentraland/explorer-desktop/releases/latest --silent | jq '.name' -r)

          # Get the commit from the last 7 characters of the version
          LAST_COMMIT_HASH=$(echo -n ${LAST_VERSION} | tail -c 7)

          # Compare and throw error if are equal
          [[ "${NEW_COMMIT_HASH}" == "${LAST_COMMIT_HASH}" ]] && echo "Error: You can't execute another release with the same commit hash that the last one" && exit 1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.number }}
          files: LICENSE