name: Checkrun!

on:
  check_run: 
    types: [ completed ]

jobs:
  release:
   concurrency: ci
   if: ${{ github.event.check_run.app.name == 'CircleCI Checks' && github.event.check_run.conclusion == 'success' && github.event.check_run.name == 'build-deploy' }} && github.event.check_run.check_suite.head_branch == 'main' }}
   runs-on: ubuntu-latest
   steps:
      - uses: hmarr/debug-action@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set version
        shell: bash
        run: |
          COMMIT_HASH=${{ github.sha }}
          DATE=$(date '+%Y%m%d%H%M%S')
          VERSION=1.0.${{github.run_number}}-${DATE}.commit-${COMMIT_HASH::7}
          echo ${VERSION}
          echo "##[set-output name=number;]$(echo ${VERSION})"
          echo ${VERSION} > hello_world
        id: set_version
      - name: Check last commit release
        shell: bash
        run: |
          # Get current commit hash
          LARGE_COMMIT_HASH=${{ github.sha }}
          NEW_COMMIT_HASH=${LARGE_COMMIT_HASH::7}

          # Fetch last version
          LAST_VERSION=$(curl https://api.github.com/repos/kuruk-mm/circleci-gh/releases/latest --silent | jq '.name' -r)
          echo ${LAST_VERSION}

          # Get the commit from the last 7 characters of the version
          LAST_COMMIT_HASH=$(echo -n "${LAST_VERSION}" | tail -c 7)

          # Compare and throw error if are equal
          echo "Last hash: ${LAST_COMMIT_HASH}"
          echo "New hash: ${NEW_COMMIT_HASH}"
          if [ "${NEW_COMMIT_HASH}" == "${LAST_COMMIT_HASH}" ]; then
            echo "Error: You can't execute another release with the same commit hash that the last one"
            exit 1
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.number }}
          files: LICENSE